services:
  node:
    image: "node:18-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./gate-simulator:/home/node/app
    ports:
      - '9999:9999'
    command: "npm start"

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass